#ifndef OTA_STATES_H
#define OTA_STATES_H

typedef enum {
    OTA_STATE_IDLE = 0,
    OTA_STATE_CHECKING_WIFI,
    OTA_STATE_PROVISIONING,
    OTA_STATE_CONNECTING,
    OTA_STATE_FETCHING_MANIFEST,
    OTA_STATE_DOWNLOADING,
    OTA_STATE_VERIFYING,
    OTA_STATE_INSTALLING,
    OTA_STATE_SUCCESS,
    OTA_STATE_FAILED
} ota_state_t;

#endif
